//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Practice.Componens
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryProduct
    {
        public int Id { get; set; }
        public Nullable<int> ContryId { get; set; }
        public Nullable<int> ProductId { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual Product Product { get; set; }
    }
}
